Finished non-functional parts of voter detail display
Exception: It always just displays the first phone number because I
don’t feel like doing the phone number part right now.